### ISSUE TITLE
Offcanvas 'Remember me' conflicting with form-login.php

### ISSUE THREAD

**Issue by cemmos** [craftwerkberlin/bootcommerce-5-child#1]
Just a small issue I noticed. Since the offcanvas login form and WooCommerce `myaccount/form-login.php` have the same IDs, we get invalid HTML markup. As well, the remember me checkbox can't be checked by clicking on the "Remember me" label because of the duplicate IDs (it works in the offcanvas form, but not on the my-account login form).

This can be seen on the official bootScore website while logged out: https://bootscore.me/account/

![duplicate-ids](https://user-images.githubusercontent.com/5217755/127783681-661cd93e-6d8f-48f4-aa4b-92b3e01dfe13.png)

**Comment by craftwerkberlin** [comment]
Hi cemmos,

you are right, thanks for the report. But it has nothing to do with the child theme, it has to be fixed in the parent. Please reopen this issue here  https://github.com/craftwerkberlin/bootscore-5/issues/new

**Comment by cemmos** [comment]
Ah, that's right. Got mixed up since I copied some of the templates over. I've reposted in the parent theme's issue tracker. Thanks.
